Update vnet-deployment.md
MicrosoftDocs/dataexplorer-docs pull request #1008
Opened 2022-01-27 16:18 UTC by bwatts64

Clarifying two things that I'm seeing customers get confused about
1) Accessing the public endpoint from outside of Azure requires a rule to be added to the NSG
2) Our current Private Link/Private Endpoint solution doesn't work if you provision Dev/Test because the load balancers are basic instead of standard

2022-01-27 17:40 UTC, ktoliver commented
#label:"aq-pr-triaged"

2022-01-30 08:09 UTC, shsagir commented
@name Thanks for contacting us with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

2022-01-30 10:15 UTC, basaba requested changes

2022-01-30 10:15 UTC, basaba commented on data-explorer/vnet-deployment.md
> +> The default NSG rules will block access to the Public IP outside of Azure. In order to reach the Public Endpoint you need to add an exception in the NSG for your Public IP address or addresses.
outside of the VNet

2022-02-01 08:46 UTC, PRMerger18 commented
@shsagir : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-02-01 08:48 UTC, shsagir commented
#sign-off
Reviewed by docs. PR Review team, please publish. Tx

2022-02-01 08:48 UTC, PRMerger12 commented
@shsagir: I'm sorry - only the author of this article, @orspod, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

2022-02-01 14:54 UTC, PRMerger14 commented
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-02-01 14:54 UTC, merged