Added await to the IngestFromStorageAsync calls
MicrosoftDocs/dataexplorer-docs pull request #690
Opened 2021-05-20 09:20 UTC by grik001

Added await to the IngestFromStorageAsync calls

2021-05-20 09:20 UTC, PRMerger17 commented
@grik001 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2021-05-20 09:55 UTC, YaelSchuster commented
Hi @grik001, you're rocking this docs contribution! Thanks!
@kerend please review

2021-05-24 07:06 UTC, vladikbr commented on data-explorer/ingest-json-formats.md
> +    await ingestClient.IngestFromStorageAsync(blobPath, properties);
```suggestion
    await ingestClient.IngestFromStorageAsync(blobPath, properties).ConfigureAwait(false);
```

2021-05-24 07:07 UTC, vladikbr commented on data-explorer/ingest-json-formats.md
> +    await ingestClient.IngestFromStorageAsync(blobPath, properties);
```suggestion
    await ingestClient.IngestFromStorageAsync(blobPath, properties).ConfigureAwait(false);
```

2021-05-24 07:07 UTC, vladikbr commented on data-explorer/ingest-json-formats.md
> +await ingestClient.IngestFromStorageAsync(blobPath, properties);
```suggestion
await ingestClient.IngestFromStorageAsync(blobPath, properties).ConfigureAwait(false);
```

2021-05-24 07:07 UTC, vladikbr commented on data-explorer/ingest-json-formats.md
> +    await ingestClient.IngestFromStorageAsync(blobPath, properties);
```suggestion
    await ingestClient.IngestFromStorageAsync(blobPath, properties).ConfigureAwait(false);
```

2021-05-24 07:07 UTC, vladikbr commented on data-explorer/ingest-json-formats.md
> +    await ingestClient.IngestFromStorageAsync(blobPath, properties);
```suggestion
    await ingestClient.IngestFromStorageAsync(blobPath, properties).ConfigureAwait(false);
```

2021-05-24 07:08 UTC, vladikbr requested changes
See change suggestions

2021-05-24 09:38 UTC, PRMerger13 commented
@grik001 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2021-05-24 10:49 UTC, YaelSchuster commented
#sign-off

2021-05-24 10:49 UTC, PRMerger18 commented
@YaelSchuster: I'm sorry - only the author of this article, @orspod, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

2021-05-24 15:58 UTC, merged