Update ingest-data-iot-hub.md
MicrosoftDocs/dataexplorer-docs pull request #822
Opened 2021-09-15 14:11 UTC by OrrinEdenfield

Removed the prerequisite of Visual Studio as it seems only .NET Core SDK is needed when users modify the sample code with another text editor.  I changed this to .NET Core SDK. This will make the instructions clearer & more inclusive to Linux users who can't easily run Visual Studio (would have also saved me time as the install for Visual Studio is much longer vs. the install for just the .NET Core SDK).

2021-09-15 14:11 UTC, PRMerger14 commented
@OrrinEdenfield : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2021-09-15 16:28 UTC, ktoliver commented
#label:"aq-pr-triaged"

2021-09-19 11:53 UTC, yogilad commented on data-explorer/ingest-data-iot-hub.md
> +* [.NET Core SDK](https://aka.ms/dotnet-download) to run the sample app.
```suggestion
* [.NET SDK] (https://dotnet.microsoft.com/download) to compile and run the sample app.
```

2021-09-19 11:55 UTC, yogilad requested changes
Specific suggestion in the comments

2021-09-19 20:00 UTC, PRMerger3 commented
@OrrinEdenfield : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2021-09-19 20:00 UTC, PRMerger3 commented
@OrrinEdenfield : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2021-09-29 10:13 UTC, YaelSchuster commented
Approved by ADX content team
#sign-off

Thanks, @OrrinEdenfield for your contribution!

2021-09-29 10:13 UTC, PRMerger12 commented
@YaelSchuster: I'm sorry - only the author of this article, @orspod, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

2021-09-29 20:25 UTC, PRMerger12 commented
@ShannonLeavitt : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2021-09-29 20:25 UTC, merged